### ISSUE TITLE
ToDo™

### ISSUE THREAD

**Issue by zeroed** [zeroed/scribbles#1]
In no particular order
- [ ] [`all`]: clean up comments and refactor duped/similar code;
- [ ] [`db`]: split the DB connections (optional MySQL or PostgreSQL);
- [ ] [`doc`]: better README;
- [ ] [`api`]: basicAuth in `create`;
- [x] [`api`]: random sentence endpoint;
- [x] [`db`]: connect to PG;
- [x] [`api`]: query with REGEX;
- [x] [`cli`]: search and highlight results;
- [ ] [`main`]: better _doctor_ (also connections);
- [ ] [`api`]: paginate the _index_;
- [x] [`api`]: limit/validate search input;
- [x] [`cli`]: make the file argument optional;
- [ ] [`cli`]: use [conduit](https://github.com/snoyberg/conduit) to read from file;
- [x] [`all`]: add a `Makefile`;
- [ ] [`cli`]: parallel insert (load file);
- [x] [`api`]: recover from `sqlErrorMsg = "connection disconnected"`;
- [ ] [`api`]: `Reader` monad to pass the `config` around;
